// Programmatic pixel art sprite definitions — Press Start! faithful
// Each sprite is a 2D array of hex color values (null = transparent)

const C = null; // Clear/transparent

// Color palette — bright, cheerful Press Start! style
const WHITE = '#ffffff';
const BLACK = '#000000';
const RABBIT_WHITE = '#f8f8f8';
const RABBIT_PINK = '#ff7eb3';
const RABBIT_RED = '#ff3b3b';
const RABBIT_EYE = '#222034';
const RABBIT_NOSE = '#ff7eb3';
const RABBIT_MOUTH = '#ff3b3b';
const GRASS_TOP = '#5ddb5d';
const GRASS_DARK = '#3dbd3d';
const DIRT = '#c4813a';
const DIRT_DARK = '#a06828';
const STONE = '#8a8a9a';
const STONE_DARK = '#6a6a7a';
const STONE_LIGHT = '#aaaaba';
const PLATFORM = '#d4a340';
const PLATFORM_LIGHT = '#f0c060';
const CARROT_ORANGE = '#ff8c00';
const CARROT_GREEN = '#3ac73a';
const HEART_RED = '#ff3b3b';
const STAR_YELLOW = '#ffe347';
const STAR_BRIGHT = '#fff8a0';
const BRICK = '#e04040';
const BRICK_DARK = '#b03030';
const SPRING_GREEN = '#3be8e8';

// Robot colors (King Viking's army)
const ROBOT_GRAY = '#8899aa';
const ROBOT_DARK = '#556677';
const ROBOT_LIGHT = '#aabbcc';
const ROBOT_RED = '#ff4444';
const ROBOT_EYE = '#ff3333';
const ROBOT_BODY = '#667788';
const ROBOT_RIVET = '#aabbcc';

// Flying robot colors
const FLY_ROBOT = '#7788cc';
const FLY_DARK = '#5566aa';
const FLY_LIGHT = '#99aadd';
const FLY_PROP = '#ccccdd';

// King Viking colors (Wario-inspired, pink skin, black mustache)
const VIKING_SKIN = '#ffb899';
const VIKING_SKIN_DARK = '#e09878';
const VIKING_HELMET = '#6644cc';
const VIKING_HELMET_DARK = '#4422aa';
const VIKING_HORN = '#ddcc44';
const VIKING_HORN_DARK = '#bbaa22';
const VIKING_MUSTACHE = '#222034';
const VIKING_CAPE = '#6644cc';
const VIKING_CAPE_DARK = '#4422aa';
const VIKING_SHIRT = '#4488dd';
const VIKING_BELT = '#ffcc33';
const VIKING_BOOT = '#4422aa';

// Super Rabbit Boy — idle frame (16x16)
// Press Start! style: white rabbit, round head, big eyes, pink inner ears
// Simple, expressive, cheerful pixel art
const RABBIT_IDLE_1 = [
  [C,C,C,C,RABBIT_WHITE,C,C,C,C,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Super Rabbit Boy — run frame 1 (legs apart)
const RABBIT_RUN_1 = [
  [C,C,C,C,RABBIT_WHITE,C,C,C,C,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,C,C,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_RED,C,C,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Super Rabbit Boy — run frame 2 (legs together)
const RABBIT_RUN_2 = [
  [C,C,C,C,RABBIT_WHITE,C,C,C,C,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Jump frame — ears back, arms up, expressive
const RABBIT_JUMP = [
  [C,C,C,RABBIT_WHITE,C,C,C,C,C,C,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_RED,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,RABBIT_WHITE,C,C,C,C],
  [RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Grass tile (16x16) — brighter, more cheerful
const TILE_GRASS = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(DIRT));
  for (let x = 0; x < 16; x++) {
    t[0][x] = GRASS_TOP;
    t[1][x] = GRASS_TOP;
    t[2][x] = (x % 3 === 0) ? GRASS_DARK : GRASS_TOP;
    t[3][x] = (x % 5 === 1) ? GRASS_DARK : GRASS_TOP;
  }
  for (let y = 4; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      t[y][x] = ((x + y) % 7 === 0) ? DIRT_DARK : DIRT;
    }
  }
  return t;
})();

// Dirt tile
const TILE_DIRT = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(DIRT));
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if ((x + y) % 7 === 0) t[y][x] = DIRT_DARK;
    }
  }
  return t;
})();

// Stone tile — Viking fortress style
const TILE_STONE = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(STONE));
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if ((x * 3 + y * 5) % 11 === 0) t[y][x] = STONE_LIGHT;
      if ((x * 7 + y * 2) % 13 === 0) t[y][x] = STONE_DARK;
    }
  }
  for (let x = 0; x < 16; x++) { t[7][x] = STONE_DARK; t[15][x] = STONE_DARK; }
  for (let y = 0; y < 8; y++) { t[y][7] = STONE_DARK; }
  for (let y = 8; y < 16; y++) { t[y][0] = STONE_DARK; t[y][15] = STONE_DARK; }
  return t;
})();

// Breakable brick tile
const TILE_BRICK = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(BRICK));
  for (let x = 0; x < 16; x++) { t[3][x] = BRICK_DARK; t[7][x] = BRICK_DARK; t[11][x] = BRICK_DARK; t[15][x] = BRICK_DARK; }
  for (let y = 0; y < 4; y++) { t[y][7] = BRICK_DARK; }
  for (let y = 4; y < 8; y++) { t[y][3] = BRICK_DARK; t[y][11] = BRICK_DARK; }
  for (let y = 8; y < 12; y++) { t[y][7] = BRICK_DARK; }
  for (let y = 12; y < 16; y++) { t[y][3] = BRICK_DARK; t[y][11] = BRICK_DARK; }
  return t;
})();

// Platform tile
const TILE_PLATFORM = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(C));
  for (let x = 0; x < 16; x++) {
    t[0][x] = PLATFORM;
    t[1][x] = PLATFORM;
    t[2][x] = PLATFORM_LIGHT;
    t[3][x] = PLATFORM;
  }
  for (let y = 4; y < 16; y++) {
    t[y][2] = PLATFORM; t[y][3] = PLATFORM_LIGHT;
    t[y][12] = PLATFORM; t[y][13] = PLATFORM_LIGHT;
  }
  return t;
})();

// Carrot collectible (16x16) — brighter
const SPRITE_CARROT = [
  [C,C,C,C,C,C,C,CARROT_GREEN,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_GREEN,CARROT_GREEN,CARROT_GREEN,C,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_GREEN,C,CARROT_GREEN,C,CARROT_GREEN,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,'#ffc060',CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,'#ffc060',CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Heart
const SPRITE_HEART = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,HEART_RED,HEART_RED,C,C,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,'#ff9999',HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C],
  [C,C,C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Star power-up — Super Carrot (special power carrot from the books)
const SPRITE_STAR = [
  [C,C,C,C,C,C,C,STAR_YELLOW,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,STAR_YELLOW,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C,C],
  [C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_BRIGHT,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_BRIGHT,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C],
  [C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Speed boost power-up (boot)
const SPRITE_SPEED = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C],
  [C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C],
  [C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C],
  [C,C,C,'#0e8888','#0e8888','#0e8888','#0e8888','#0e8888','#0e8888','#0e8888',C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Robot enemy (ground patrol) — King Viking's robot minion (16x16)
const SPRITE_ROBOT = [
  [C,C,C,C,C,C,ROBOT_RED,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,ROBOT_GRAY,ROBOT_LIGHT,ROBOT_GRAY,C,C,C,C,C,C,C,C],
  [C,C,C,C,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,C,C,C,C,C,C,C],
  [C,C,C,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,C,C,C,C,C,C],
  [C,C,C,ROBOT_GRAY,ROBOT_EYE,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_EYE,ROBOT_GRAY,C,C,C,C,C,C],
  [C,C,C,ROBOT_GRAY,ROBOT_EYE,ROBOT_GRAY,ROBOT_GRAY,ROBOT_GRAY,ROBOT_EYE,ROBOT_GRAY,C,C,C,C,C,C],
  [C,C,C,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,C,C,C,C,C,C],
  [C,C,C,C,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,C,C,C,C,C,C,C],
  [C,C,ROBOT_GRAY,ROBOT_BODY,ROBOT_BODY,ROBOT_RIVET,ROBOT_BODY,ROBOT_RIVET,ROBOT_BODY,ROBOT_GRAY,C,C,C,C,C,C],
  [C,C,ROBOT_GRAY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_GRAY,C,C,C,C,C,C],
  [C,C,C,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,C,C,C,C,C,C,C],
  [C,C,C,C,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,ROBOT_BODY,C,C,C,C,C,C,C,C],
  [C,C,C,C,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,ROBOT_DARK,C,C,C,C,C,C,C,C],
  [C,C,C,ROBOT_DARK,ROBOT_DARK,C,C,ROBOT_DARK,ROBOT_DARK,C,C,C,C,C,C,C],
  [C,C,C,ROBOT_DARK,ROBOT_DARK,C,C,ROBOT_DARK,ROBOT_DARK,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Flying Robot enemy (16x16) — propeller drone
const SPRITE_FLY_ROBOT = [
  [C,C,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,C,C,C,C,C],
  [C,C,C,C,C,C,FLY_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,FLY_ROBOT,FLY_LIGHT,FLY_ROBOT,C,C,C,C,C,C,C,C],
  [C,C,C,C,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,C,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C],
  [C,C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C,C],
  [C,C,C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,FLY_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Flying Robot — propeller spin alternate frame
const SPRITE_FLY_ROBOT_UP = [
  [C,C,C,C,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,FLY_PROP,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,FLY_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,FLY_ROBOT,FLY_LIGHT,FLY_ROBOT,C,C,C,C,C,C,C,C],
  [C,C,C,C,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,C,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,FLY_ROBOT,FLY_ROBOT,ROBOT_EYE,FLY_ROBOT,C,C,C,C,C,C],
  [C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C],
  [C,C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C,C],
  [C,C,C,C,C,FLY_DARK,FLY_DARK,FLY_DARK,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,FLY_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// King Viking boss (16x16, rendered at 2x) — purple helmet, horns, pink skin, black mustache
const SPRITE_KING_VIKING = [
  [C,VIKING_HORN,C,C,C,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,C,C,C,VIKING_HORN,C,C,C,C],
  [C,VIKING_HORN_DARK,C,C,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,C,C,VIKING_HORN_DARK,C,C,C,C],
  [C,C,C,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,VIKING_HELMET,C,C,C,C,C,C],
  [C,C,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,C,C,C,C,C],
  [C,C,VIKING_SKIN,VIKING_SKIN,RABBIT_EYE,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,RABBIT_EYE,VIKING_SKIN,VIKING_SKIN,C,C,C,C,C],
  [C,C,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN_DARK,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,C,C,C,C,C],
  [C,C,C,VIKING_MUSTACHE,VIKING_MUSTACHE,VIKING_MUSTACHE,VIKING_MUSTACHE,VIKING_MUSTACHE,VIKING_MUSTACHE,VIKING_MUSTACHE,C,C,C,C,C,C],
  [C,C,C,C,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,C,C,C,C,C,C,C],
  [C,C,VIKING_CAPE,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_CAPE,C,C,C,C,C,C],
  [C,VIKING_CAPE,VIKING_CAPE,VIKING_SHIRT,VIKING_SHIRT,VIKING_BELT,VIKING_BELT,VIKING_SHIRT,VIKING_SHIRT,VIKING_CAPE,VIKING_CAPE,C,C,C,C,C],
  [C,VIKING_CAPE_DARK,C,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,VIKING_SHIRT,C,VIKING_CAPE_DARK,C,C,C,C,C],
  [C,C,C,C,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,VIKING_SKIN,C,C,C,C,C,C,C,C],
  [C,C,C,VIKING_BOOT,VIKING_BOOT,VIKING_BOOT,C,VIKING_BOOT,VIKING_BOOT,VIKING_BOOT,C,C,C,C,C,C],
  [C,C,C,VIKING_BOOT,VIKING_BOOT,VIKING_BOOT,C,VIKING_BOOT,VIKING_BOOT,VIKING_BOOT,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Checkpoint flag (16x16)
const SPRITE_CHECKPOINT = [
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,'#ff9999',RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,STONE,STONE,STONE,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,STONE,STONE,STONE,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Sprite cache for pre-rendered canvases
const spriteCache = new Map();

export class SpriteRenderer {
  constructor() {
    this.sprites = {
      rabbitIdle: [RABBIT_IDLE_1],
      rabbitRun: [RABBIT_RUN_1, RABBIT_RUN_2],
      rabbitJump: [RABBIT_JUMP],
      tileGrass: TILE_GRASS,
      tileDirt: TILE_DIRT,
      tileStone: TILE_STONE,
      tileBrick: TILE_BRICK,
      tilePlatform: TILE_PLATFORM,
      carrot: SPRITE_CARROT,
      heart: SPRITE_HEART,
      star: SPRITE_STAR,
      speed: SPRITE_SPEED,
      fox: [SPRITE_ROBOT],
      bird: [SPRITE_FLY_ROBOT, SPRITE_FLY_ROBOT_UP],
      kingFox: [SPRITE_KING_VIKING],
      checkpoint: SPRITE_CHECKPOINT,
    };
  }

  // Pre-render a pixel art sprite to an offscreen canvas
  _renderToCanvas(spriteData, scale = 1, flipX = false) {
    const key = JSON.stringify(spriteData) + scale + flipX;
    if (spriteCache.has(key)) return spriteCache.get(key);

    const h = spriteData.length;
    const w = spriteData[0].length;
    const canvas = document.createElement('canvas');
    canvas.width = w * scale;
    canvas.height = h * scale;
    const ctx = canvas.getContext('2d');

    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const color = spriteData[y][x];
        if (color) {
          ctx.fillStyle = color;
          const drawX = flipX ? (w - 1 - x) * scale : x * scale;
          ctx.fillRect(drawX, y * scale, scale, scale);
        }
      }
    }

    spriteCache.set(key, canvas);
    return canvas;
  }

  // Draw a sprite at the given position (in game pixels, before camera transform)
  draw(ctx, name, x, y, frame = 0, flipX = false, scale = 1) {
    const spriteData = Array.isArray(this.sprites[name])
      ? (Array.isArray(this.sprites[name][0]?.[0]) ? this.sprites[name][frame] : this.sprites[name])
      : this.sprites[name];

    if (!spriteData) return;

    const canvas = this._renderToCanvas(spriteData, scale, flipX);
    ctx.drawImage(canvas, Math.floor(x), Math.floor(y));
  }

  // Get sprite dimensions
  getSize(name, scale = 1) {
    const spriteData = Array.isArray(this.sprites[name])
      ? (Array.isArray(this.sprites[name][0]?.[0]) ? this.sprites[name][0] : this.sprites[name])
      : this.sprites[name];
    if (!spriteData) return { w: 0, h: 0 };
    return { w: spriteData[0].length * scale, h: spriteData.length * scale };
  }
}
