// Programmatic pixel art sprite definitions
// Each sprite is a 2D array of hex color values (null = transparent)

const C = null; // Clear/transparent

// Color palette
const WHITE = '#ffffff';
const BLACK = '#000000';
const RABBIT_WHITE = '#f0f0f0';
const RABBIT_PINK = '#ff6b8a';
const RABBIT_RED = '#e63946';
const RABBIT_DARK = '#2b2b2b';
const RABBIT_EYE = '#1a1a2e';
const RABBIT_CAPE = '#e63946';
const GRASS_TOP = '#4ade80';
const GRASS_DARK = '#22c55e';
const DIRT = '#92400e';
const DIRT_DARK = '#78350f';
const STONE = '#9ca3af';
const STONE_DARK = '#6b7280';
const STONE_LIGHT = '#d1d5db';
const SKY = '#87ceeb';
const PLATFORM = '#a16207';
const PLATFORM_LIGHT = '#ca8a04';
const CARROT_ORANGE = '#f97316';
const CARROT_GREEN = '#16a34a';
const HEART_RED = '#ef4444';
const HEART_DARK = '#b91c1c';
const STAR_YELLOW = '#fbbf24';
const STAR_DARK = '#f59e0b';
const FOX_ORANGE = '#ea580c';
const FOX_DARK = '#c2410c';
const FOX_WHITE = '#fff7ed';
const BIRD_BLUE = '#3b82f6';
const BIRD_DARK = '#1d4ed8';
const KING_PURPLE = '#7c3aed';
const KING_DARK = '#5b21b6';
const KING_GOLD = '#fbbf24';
const BRICK = '#dc2626';
const BRICK_DARK = '#991b1b';
const SPRING_GREEN = '#22d3ee';

// Super Rabbit Boy — idle frame (16x16)
const RABBIT_IDLE_1 = [
  [C,C,C,C,C,RABBIT_PINK,C,C,C,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_PINK,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Super Rabbit Boy — run frame 1
const RABBIT_RUN_1 = [
  [C,C,C,C,C,RABBIT_PINK,C,C,C,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_PINK,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_RED,RABBIT_RED,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Super Rabbit Boy — run frame 2
const RABBIT_RUN_2 = [
  [C,C,C,C,C,RABBIT_PINK,C,C,C,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_PINK,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [C,C,C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Jump frame
const RABBIT_JUMP = [
  [C,C,C,C,RABBIT_PINK,C,C,C,C,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,RABBIT_PINK,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_PINK,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_PINK,RABBIT_PINK,RABBIT_PINK,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_EYE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_PINK,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C],
  [C,RABBIT_CAPE,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C,C],
  [RABBIT_CAPE,RABBIT_CAPE,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,RABBIT_CAPE,RABBIT_CAPE,C,C,C,C],
  [C,C,C,C,RABBIT_CAPE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,RABBIT_CAPE,C,C,C,C,C,C,C],
  [C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,C],
  [C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C,RABBIT_WHITE,RABBIT_WHITE,C,C,C,C,C],
  [C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C,RABBIT_RED,RABBIT_RED,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Grass tile (16x16)
const TILE_GRASS = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(DIRT));
  // Top grass surface
  for (let x = 0; x < 16; x++) {
    t[0][x] = GRASS_TOP;
    t[1][x] = GRASS_TOP;
    t[2][x] = (x % 3 === 0) ? GRASS_DARK : GRASS_TOP;
    t[3][x] = (x % 4 === 1) ? GRASS_DARK : GRASS_TOP;
  }
  // Dirt with variation
  for (let y = 4; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      t[y][x] = ((x + y) % 7 === 0) ? DIRT_DARK : DIRT;
    }
  }
  return t;
})();

// Dirt tile
const TILE_DIRT = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(DIRT));
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if ((x + y) % 7 === 0) t[y][x] = DIRT_DARK;
    }
  }
  return t;
})();

// Stone tile
const TILE_STONE = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(STONE));
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if ((x * 3 + y * 5) % 11 === 0) t[y][x] = STONE_LIGHT;
      if ((x * 7 + y * 2) % 13 === 0) t[y][x] = STONE_DARK;
    }
  }
  // Mortar lines
  for (let x = 0; x < 16; x++) { t[7][x] = STONE_DARK; t[15][x] = STONE_DARK; }
  for (let y = 0; y < 8; y++) { t[y][7] = STONE_DARK; }
  for (let y = 8; y < 16; y++) { t[y][0] = STONE_DARK; t[y][15] = STONE_DARK; }
  return t;
})();

// Breakable brick tile
const TILE_BRICK = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(BRICK));
  for (let x = 0; x < 16; x++) { t[3][x] = BRICK_DARK; t[7][x] = BRICK_DARK; t[11][x] = BRICK_DARK; t[15][x] = BRICK_DARK; }
  for (let y = 0; y < 4; y++) { t[y][7] = BRICK_DARK; }
  for (let y = 4; y < 8; y++) { t[y][3] = BRICK_DARK; t[y][11] = BRICK_DARK; }
  for (let y = 8; y < 12; y++) { t[y][7] = BRICK_DARK; }
  for (let y = 12; y < 16; y++) { t[y][3] = BRICK_DARK; t[y][11] = BRICK_DARK; }
  return t;
})();

// Platform tile (one-way)
const TILE_PLATFORM = (() => {
  const t = Array.from({ length: 16 }, () => Array(16).fill(C));
  for (let x = 0; x < 16; x++) {
    t[0][x] = PLATFORM;
    t[1][x] = PLATFORM;
    t[2][x] = PLATFORM_LIGHT;
    t[3][x] = PLATFORM;
  }
  // Support pillars
  for (let y = 4; y < 16; y++) {
    t[y][2] = PLATFORM; t[y][3] = PLATFORM_LIGHT;
    t[y][12] = PLATFORM; t[y][13] = PLATFORM_LIGHT;
  }
  return t;
})();

// Carrot collectible (16x16)
const SPRITE_CARROT = [
  [C,C,C,C,C,C,C,CARROT_GREEN,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_GREEN,CARROT_GREEN,CARROT_GREEN,C,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_GREEN,C,CARROT_GREEN,C,CARROT_GREEN,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,'#fdba74',CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,CARROT_ORANGE,CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,CARROT_ORANGE,'#fdba74',CARROT_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,CARROT_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Heart
const SPRITE_HEART = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,HEART_RED,HEART_RED,C,C,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,'#fca5a5',HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C],
  [C,C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C],
  [C,C,C,HEART_RED,HEART_RED,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,HEART_RED,HEART_RED,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Star power-up
const SPRITE_STAR = [
  [C,C,C,C,C,C,C,STAR_YELLOW,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,STAR_YELLOW,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C,C],
  [C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,'#fef3c7',STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C],
  [C,C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,STAR_YELLOW,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C],
  [C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C,C,C,STAR_YELLOW,STAR_YELLOW,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Speed boost power-up (boot)
const SPRITE_SPEED = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C,C,C],
  [C,C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C,C],
  [C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C],
  [C,C,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,SPRING_GREEN,C,C,C,C,C],
  [C,C,C,'#0e7490','#0e7490','#0e7490','#0e7490','#0e7490','#0e7490','#0e7490',C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Fox enemy (16x16)
const SPRITE_FOX = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C],
  [C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C],
  [C,FOX_ORANGE,FOX_WHITE,FOX_ORANGE,C,C,C,C,FOX_ORANGE,FOX_WHITE,FOX_ORANGE,C,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C],
  [C,C,C,FOX_ORANGE,BLACK,FOX_ORANGE,FOX_ORANGE,BLACK,FOX_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_WHITE,FOX_WHITE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,FOX_DARK,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_DARK,C,C,C,C,C,C,C],
  [C,C,FOX_DARK,FOX_DARK,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_DARK,FOX_DARK,C,C,C,C,C,C],
  [C,C,C,C,FOX_ORANGE,FOX_WHITE,FOX_WHITE,FOX_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C,C,C],
  [C,C,C,FOX_DARK,FOX_DARK,C,C,FOX_DARK,FOX_DARK,C,C,C,C,C,C,C],
  [C,C,C,FOX_DARK,FOX_DARK,C,C,FOX_DARK,FOX_DARK,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Bird enemy (16x16)
const SPRITE_BIRD = [
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,BIRD_BLUE,C,C,C,C,C,C,C,BIRD_BLUE,C,C,C,C,C],
  [C,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C],
  [BIRD_BLUE,BIRD_DARK,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_DARK,BIRD_BLUE,C,C,C,C],
  [C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,BIRD_BLUE,BLACK,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BLACK,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,C,BIRD_BLUE,BIRD_BLUE,CARROT_ORANGE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,C],
  [C,C,C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,BIRD_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Bird with wings up
const SPRITE_BIRD_UP = [
  [C,C,BIRD_BLUE,C,C,C,C,C,C,C,BIRD_BLUE,C,C,C,C,C],
  [C,BIRD_BLUE,BIRD_DARK,C,C,C,C,C,C,BIRD_DARK,BIRD_BLUE,C,C,C,C,C],
  [C,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C],
  [C,C,BIRD_BLUE,C,C,C,C,C,C,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,BIRD_BLUE,BLACK,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BLACK,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C],
  [C,C,C,C,BIRD_BLUE,BIRD_BLUE,CARROT_ORANGE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,C],
  [C,C,C,C,C,BIRD_BLUE,BIRD_BLUE,BIRD_BLUE,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,BIRD_DARK,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// King Fox boss (32x32 — double size, stored as 16x16 and rendered at 2x)
const SPRITE_KING_FOX = [
  [C,C,C,KING_GOLD,KING_GOLD,KING_GOLD,C,C,C,KING_GOLD,KING_GOLD,KING_GOLD,C,C,C,C],
  [C,C,C,C,KING_GOLD,STAR_YELLOW,C,C,C,STAR_YELLOW,KING_GOLD,C,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,KING_GOLD,KING_GOLD,KING_GOLD,KING_GOLD,KING_GOLD,KING_GOLD,FOX_ORANGE,FOX_ORANGE,C,C,C,C],
  [C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C],
  [C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,HEART_RED,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,HEART_RED,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C],
  [C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_WHITE,FOX_WHITE,FOX_WHITE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C],
  [C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C],
  [C,C,KING_PURPLE,KING_PURPLE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,KING_PURPLE,KING_PURPLE,C,C,C,C,C],
  [C,KING_PURPLE,KING_PURPLE,KING_PURPLE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,KING_PURPLE,KING_PURPLE,KING_PURPLE,C,C,C,C],
  [C,KING_PURPLE,C,KING_PURPLE,KING_PURPLE,FOX_WHITE,FOX_WHITE,FOX_WHITE,KING_PURPLE,KING_PURPLE,C,KING_PURPLE,C,C,C,C],
  [C,C,C,C,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,FOX_ORANGE,C,C,C,C,C,C,C],
  [C,C,C,FOX_DARK,FOX_DARK,FOX_DARK,C,FOX_DARK,FOX_DARK,FOX_DARK,C,C,C,C,C,C],
  [C,C,C,FOX_DARK,FOX_DARK,FOX_DARK,C,FOX_DARK,FOX_DARK,FOX_DARK,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Checkpoint flag (16x16)
const SPRITE_CHECKPOINT = [
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,'#fca5a5',RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C],
  [C,C,C,RABBIT_RED,RABBIT_RED,RABBIT_RED,RABBIT_RED,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,STONE,C,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,STONE,STONE,STONE,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,STONE,STONE,STONE,C,C,C,C,C,C,C,C,C,C,C],
  [C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C],
];

// Sprite cache for pre-rendered canvases
const spriteCache = new Map();

export class SpriteRenderer {
  constructor() {
    this.sprites = {
      rabbitIdle: [RABBIT_IDLE_1],
      rabbitRun: [RABBIT_RUN_1, RABBIT_RUN_2],
      rabbitJump: [RABBIT_JUMP],
      tileGrass: TILE_GRASS,
      tileDirt: TILE_DIRT,
      tileStone: TILE_STONE,
      tileBrick: TILE_BRICK,
      tilePlatform: TILE_PLATFORM,
      carrot: SPRITE_CARROT,
      heart: SPRITE_HEART,
      star: SPRITE_STAR,
      speed: SPRITE_SPEED,
      fox: [SPRITE_FOX],
      bird: [SPRITE_BIRD, SPRITE_BIRD_UP],
      kingFox: [SPRITE_KING_FOX],
      checkpoint: SPRITE_CHECKPOINT,
    };
  }

  // Pre-render a pixel art sprite to an offscreen canvas
  _renderToCanvas(spriteData, scale = 1, flipX = false) {
    const key = JSON.stringify(spriteData) + scale + flipX;
    if (spriteCache.has(key)) return spriteCache.get(key);

    const h = spriteData.length;
    const w = spriteData[0].length;
    const canvas = document.createElement('canvas');
    canvas.width = w * scale;
    canvas.height = h * scale;
    const ctx = canvas.getContext('2d');

    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const color = spriteData[y][x];
        if (color) {
          ctx.fillStyle = color;
          const drawX = flipX ? (w - 1 - x) * scale : x * scale;
          ctx.fillRect(drawX, y * scale, scale, scale);
        }
      }
    }

    spriteCache.set(key, canvas);
    return canvas;
  }

  // Draw a sprite at the given position (in game pixels, before camera transform)
  draw(ctx, name, x, y, frame = 0, flipX = false, scale = 1) {
    const spriteData = Array.isArray(this.sprites[name])
      ? (Array.isArray(this.sprites[name][0]?.[0]) ? this.sprites[name][frame] : this.sprites[name])
      : this.sprites[name];

    if (!spriteData) return;

    const canvas = this._renderToCanvas(spriteData, scale, flipX);
    ctx.drawImage(canvas, Math.floor(x), Math.floor(y));
  }

  // Get sprite dimensions
  getSize(name, scale = 1) {
    const spriteData = Array.isArray(this.sprites[name])
      ? (Array.isArray(this.sprites[name][0]?.[0]) ? this.sprites[name][0] : this.sprites[name])
      : this.sprites[name];
    if (!spriteData) return { w: 0, h: 0 };
    return { w: spriteData[0].length * scale, h: spriteData.length * scale };
  }
}
